"""Content & Asset Generation Tools for BuilderForge Creator Agent."""

from __future__ import annotations

import logging
import json
from typing import Dict, Any, List

logger = logging.getLogger(__name__)


def generate_tokenomics_model(project_title: str, category: str = "General") -> Dict[str, Any]:
    """Generate structured tokenomics distribution and token specs."""
    clean_name = "".join(e for e in project_title if e.isalnum()) or "Builder"
    symbol = (clean_name[:4].upper() or "FORGE")
    
    return {
        "token_name": f"{project_title} Token",
        "token_symbol": symbol,
        "total_supply": "100,000,000",
        "allocations": {
            "Community & Ecosystem Grants": "45%",
            "Core Team & Contributors (2 yr vesting)": "20%",
            "Public Token Launch & Liquidity Pool": "15%",
            "OKX ASP Treasury & Staking Rewards": "12%",
            "Advisors & Early Backers": "8%",
        },
        "utility": [
            "Governance voting on multi-agent protocol parameters",
            "Payment currency for ordering autonomous agent jobs",
            "Staking mechanism for Agentic Service Provider (ASP) reputation nodes",
        ]
    }


def generate_solidity_contract(token_name: str, token_symbol: str) -> str:
    """Generate production-ready OpenZeppelin ERC-20 Solidity smart contract code."""
    return f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title {token_name} ({token_symbol})
 * @dev Autonomous Agentic Token for OKX X Layer Ecosystem.
 * Generated by BuilderForge OKX Agentic Service Provider (ASP).
 */

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract {token_symbol}Token is ERC20, ERC20Burnable, Ownable {{
    uint256 public constant INITIAL_SUPPLY = 100_000_000 * 10**18;
    
    event ASPDeployed(address indexed owner, uint256 initialSupply);

    constructor(address initialOwner) 
        ERC20("{token_name}", "{token_symbol}") 
        Ownable(initialOwner) 
    {{
        _mint(initialOwner, INITIAL_SUPPLY);
        emit ASPDeployed(initialOwner, INITIAL_SUPPLY);
    }}

    /**
     * @notice Mint additional tokens for ecosystem rewards.
     */
    function mintEcosystemReward(address to, uint256 amount) external onlyOwner {{
        _mint(to, amount);
    }}
}}
"""


def generate_pitch_deck(project_title: str, description: str) -> Dict[str, Any]:
    """Generate pitch deck slides and marketing hooks."""
    return {
        "pitch_tagline": f"{project_title} – Autonomous Web3 Execution powered by BuilderForge ASP on OKX",
        "elevator_pitch": f"{project_title} solves Web3 launching friction by turning human vision ({description[:80]}...) into automated tokenomics, smart contracts, and OKX X Layer deployment within 90 seconds.",
        "key_features": [
            "Multi-Agent Crew Pipeline (Researcher → Creator → Executor → Analyzer)",
            "Native OKX Wallet & X Layer Testnet One-Click Deployment",
            "Listable Agentic Service Provider (ASP) Manifest for OKX.AI Marketplace",
            "Zero-friction automated tokenomics & Solidity code synthesis",
        ],
        "marketing_hooks": [
            f"🚀 {project_title} is live! Launching the future of Web3 with BuilderForge on OKX X Layer.",
            f"🤖 Autonomous Agents just built {project_title} in under 60 seconds. Check out our tokenomics!",
        ],
    }


def generate_asp_manifest_json(project_title: str, description: str, project_id: str) -> Dict[str, Any]:
    """Generate official OKX.AI ASP Service Manifest JSON."""
    return {
        "schema_version": "1.0.0",
        "provider": {
            "name": f"BuilderForge - {project_title}",
            "service_id": f"asp.builderforge.{project_id}",
            "description": description,
            "url": f"https://builderforge.okx.ai/projects/{project_id}",
            "version": "1.0.0",
            "author": "BuilderForge OKX Hackathon Crew",
        },
        "agents": [
            {"id": "coordinator", "name": "Coordinator Agent", "role": "Pipeline Orchestrator"},
            {"id": "researcher", "name": "Researcher Agent", "role": "DealFlow & Market Intelligence"},
            {"id": "creator", "name": "Creator Agent", "role": "LaunchPad & Asset Synthesis"},
            {"id": "executor", "name": "Executor Agent", "role": "OKX X Layer Deployment & Web3 Simulation"},
            {"id": "analyzer", "name": "Analyzer Agent", "role": "ASP Metrics & Readiness Scoring"},
        ],
        "pricing_models": [
            {"model_id": "pay_per_job", "name": "Pay Per Launch", "price": "0.05", "currency": "OKT"},
            {"model_id": "subscription", "name": "Builder Pro", "price": "10.0", "currency": "OKT/month"},
        ],
        "service_slas": {
            "uptime_guarantee_pct": 99.9,
            "max_response_time_sec": 45,
            "supported_chains": ["OKX X Layer Testnet (Chain ID 195)", "OKX Mainnet"],
        },
        "marketplace_listing": {
            "category": "Web3 Launchpad & Tokenomics ASP",
            "status": "VERIFIED_ASP_READY",
            "reputation_score": 98,
        }
    }
