/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AspListingRouteImport } from './routes/asp-listing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DealflowRouteImport } from './routes/dealflow'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as NewProjectRouteImport } from './routes/new-project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AspListingRoute = AspListingRouteImport.update({
  id: '/asp-listing',
  path: '/asp-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DealflowRoute = DealflowRouteImport.update({
  id: '/dealflow',
  path: '/dealflow',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const NewProjectRoute = NewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asp-listing': typeof AspListingRoute
  '/dashboard': typeof DashboardRoute
  '/dealflow': typeof DealflowRoute
  '/launchpad': typeof LaunchpadRoute
  '/new-project': typeof NewProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asp-listing': typeof AspListingRoute
  '/dashboard': typeof DashboardRoute
  '/dealflow': typeof DealflowRoute
  '/launchpad': typeof LaunchpadRoute
  '/new-project': typeof NewProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asp-listing': typeof AspListingRoute
  '/dashboard': typeof DashboardRoute
  '/dealflow': typeof DealflowRoute
  '/launchpad': typeof LaunchpadRoute
  '/new-project': typeof NewProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asp-listing'
    | '/dashboard'
    | '/dealflow'
    | '/launchpad'
    | '/new-project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asp-listing'
    | '/dashboard'
    | '/dealflow'
    | '/launchpad'
    | '/new-project'
  id:
    | '__root__'
    | '/'
    | '/asp-listing'
    | '/dashboard'
    | '/dealflow'
    | '/launchpad'
    | '/new-project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AspListingRoute: typeof AspListingRoute
  DashboardRoute: typeof DashboardRoute
  DealflowRoute: typeof DealflowRoute
  LaunchpadRoute: typeof LaunchpadRoute
  NewProjectRoute: typeof NewProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asp-listing': {
      id: '/asp-listing'
      path: '/asp-listing'
      fullPath: '/asp-listing'
      preLoaderRoute: typeof AspListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealflow': {
      id: '/dealflow'
      path: '/dealflow'
      fullPath: '/dealflow'
      preLoaderRoute: typeof DealflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-project': {
      id: '/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof NewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AspListingRoute: AspListingRoute,
  DashboardRoute: DashboardRoute,
  DealflowRoute: DealflowRoute,
  LaunchpadRoute: LaunchpadRoute,
  NewProjectRoute: NewProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
